[metadata]
name = starlink-grpc-core
url = https://github.com/Sike42WB/starlink-grpc-tools
author = "Michael Armondo Disanto"
author_email = sike42@outlook.com
license = Unlicense
license_files = LICENSE
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Topic :: Software Development :: Libraries :: Python Modules
description = Core functions for Starlink gRPC communication
long_description = file: README.md
long_description_content_type = text/markdown

[options]
install_requires =
    grpcio>=1.12.0
    protobuf>=3.6.0
    yagrc>=1.1.1
    typing-extensions>=4.3.0
package_dir =
    =..
py_modules =
    starlink_grpc
python_requires = >=3.7
